title: 常憂堂
lang: zh
description: 謹京的博客。
logo_img: /assets/img/icons/yuuko.svg
theme: jekyll-theme-simplex

logo_img: /assets/img/icons/yuuko.svg
copyright: © 2022 by 謹京@常憂堂

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
      
nav:
 - name: 首頁
   link: /
 - name: 發文
   link: /blogpost/
 - name: 文摘
   link: /piece/
