title: WorrizitChin's Blog 『謹京的博客』
description: 単純な 馬鹿でありたい。
logo_img: /assets/img/icons/yuuko.jpg
theme: jekyll-theme-simplex

logo_img: /assets/img/icons/yuuko.jpg
copyright: © 2022 by 謹京@常憂堂

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
