title: 常憂堂
lang: zh
description: 謹京的博客。
logo_img: /assets/image/icons/yuuko.svg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
copyright  : © 2022 by 謹京@常憂堂  

nav:
 - name: 詩
   link: /poem/
 - name: 隨筆
   link: /essay/
 - name: 音韻學
   link: /chinese-phonetics/
 - name: 語言學
   link: /linguistics/
 - name: 自娛自樂
   link: /sjewh/
